server {
    listen 80;
    server_name _;  
    
    # Frontend React
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
        
        # Cache para archivos estáticos (mejor rendimiento)
        location ~* \.(js|css|png|jpg)$ {
            expires 365d;
            add_header Cache-Control "public, immutable";
        }
    }

    # Backend API
    location /api/ {
        proxy_pass http://backend:3001;
        proxy_set_header Host $host;
    }

    # WebSockets
    location /socket.io/ {
        proxy_pass http://backend:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }
}