name: tfg-digital-twin

services:
  backend:
    build:
      context: ./backend
      target: development
    volumes:
      - ./backend:/app       # Monta el código fuente
      - /app/node_modules    # Evita sobrescribir dependencias
    environment:
      - NODE_ENV=development
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3001  # Variables aquí
    ports:
      - "5173:5173"

  ml-api:
    build: 
      context: ./ml-api
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./ml-api:/app
    networks:
      - tfg-digital-twin
    ports:
      - "8000:8000"

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    env_file:
      - .env
    volumes:
      - influxdb:/var/lib/influxdb

networks:
  tfg-digital-twin:
    driver: bridge

volumes:
  influxdb: