name: tfg-digital-twin

services:
  backend: 
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - tfg-digital-twin
    ports:
      - "3001:3001"

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - tfg-digital-twin
    ports:
      - "5173:5173"
    command: npm run dev -- --host

  ml-api:
    build: 
      context: ./ml-api
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./ml-api:/app
    networks:
      - tfg-digital-twin
    ports:
      - "8000:8000"

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    env_file:
      - .env
    volumes:
      - influxdb:/var/lib/influxdb
networks:
  tfg-digital-twin:
    driver: bridge

volumes:
  influxdb: