services:
  backend:
    build:
      context: ./backend
      target: production
    environment:
      - PORT=3001
      - NODE_ENV=production
      - ML_API_URL=http://ml-api:8000  # asegúrate de usar la URL correcta si depende de ML
    ports:
      - "3001:3001"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - tfg-digital-twin
    depends_on:
      - ml-api
      - influxdb
      - mongodb

  frontend:
    build:
      context: ./frontend
      target: production
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://backend:3001  # Mejor usar nombre de servicio, no hardcode URL
    ports:
      - "80:80"
    networks:
      - tfg-digital-twin
    depends_on:
      - backend

  ml-api:
    build:
      context: ./ml-api
    environment:
      - ENVIRONMENT=production
    ports:
      - "8000:8000"
    networks:
      - tfg-digital-twin

  influxdb:
    image: influxdb:2.7
    volumes:
      - influxdb:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=user
      - DOCKER_INFLUXDB_INIT_PASSWORD=pass
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
    ports:
      - "8086:8086"
    networks:
      - tfg-digital-twin

  mongodb:
    build:
      context: ./mongodb
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongodb:/data/db
    networks:
      - tfg-digital-twin

networks:
  tfg-digital-twin:
    driver: bridge

volumes:
  influxdb:
  mongodb:
