/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\horizontalTankModel\2Pales\horizontalTank2Blades.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('./horizontalTankModel/2Pales/horizontalTank2Blades.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Blade2.geometry} material={materials['BladeMaterial.002']} position={[0, 0.737, 0.918]} scale={-0.148} />
      <mesh geometry={nodes.MilkCilinder25.geometry} material={materials['MilkMaterial.003']} position={[-0.026, 1.597, -0.096]} scale={[2.531, 2.531, 2.615]} />
      <mesh geometry={nodes.MilkCilinder50.geometry} material={materials['MilkMaterial.003']} position={[-0.026, 1.597, -0.096]} scale={[2.531, 2.531, 2.615]} />
      <mesh geometry={nodes.MilkCilinder75.geometry} material={materials['MilkMaterial.003']} position={[-0.026, 1.597, -0.096]} scale={[2.531, 2.531, 2.615]} />
      <mesh geometry={nodes.MilkCilinder100.geometry} material={materials['MilkMaterial.003']} position={[-0.026, 1.597, -0.096]} scale={[2.531, 2.531, 2.615]} />
      <mesh geometry={nodes.Blade1.geometry} material={materials['BladeMaterial.002']} position={[0, 0.737, -0.982]} scale={-0.148} />
      <mesh geometry={nodes.Hatch.geometry} material={materials['HatchMaterial.002']} position={[0, 2.377, -0.206]} />
      <mesh geometry={nodes.TankCilinder.geometry} material={materials['TankMaterial.002']} position={[0.548, 0.399, -1.476]} />
      <mesh geometry={nodes.Blade2Hat.geometry} material={materials['BladeMaterial.002']} position={[-0.003, 2.451, 0.916]} scale={[0.107, 0.078, 0.107]} />
      <mesh geometry={nodes.Blade1Hat.geometry} material={materials['BladeMaterial.002']} position={[-0.003, 2.451, -0.988]} scale={[0.104, 0.076, 0.104]} />
      <mesh geometry={nodes.MilkCilinder10.geometry} material={materials['MilkMaterial.003']} position={[-0.026, 1.597, -0.096]} scale={[2.531, 2.531, 2.615]} />
      <mesh geometry={nodes.MilkCilinder20.geometry} material={materials['MilkMaterial.003']} position={[-0.026, 1.597, -0.096]} scale={[2.531, 2.531, 2.615]} />
      <mesh geometry={nodes.MilkCilinder30.geometry} material={materials['MilkMaterial.003']} position={[-0.026, 1.597, -0.096]} scale={[2.531, 2.531, 2.615]} />
      <mesh geometry={nodes.MilkCilinder40.geometry} material={materials['MilkMaterial.003']} position={[-0.026, 1.597, -0.096]} scale={[2.531, 2.531, 2.615]} />
      <mesh geometry={nodes.MilkCilinder60.geometry} material={materials['MilkMaterial.003']} position={[-0.026, 1.597, -0.096]} scale={[2.531, 2.531, 2.615]} />
      <mesh geometry={nodes.MilkCilinder70.geometry} material={materials['MilkMaterial.003']} position={[-0.026, 1.597, -0.096]} scale={[2.531, 2.531, 2.615]} />
      <mesh geometry={nodes.MilkCilinder80.geometry} material={materials['MilkMaterial.003']} position={[-0.026, 1.597, -0.096]} scale={[2.531, 2.531, 2.615]} />
      <mesh geometry={nodes.MilkCilinder90.geometry} material={materials['MilkMaterial.003']} position={[-0.026, 1.597, -0.096]} scale={[2.531, 2.531, 2.615]} />
      <mesh geometry={nodes.BarrelAlcaline.geometry} material={nodes.BarrelAlcaline.material} position={[1.356, 0.27, 2.848]} />
      <mesh geometry={nodes.BarrelAcid.geometry} material={nodes.BarrelAcid.material} position={[2.204, 0.27, 3.091]} />
      <mesh name="AlcalineCilinder" geometry={nodes.AlcalineCilinder.geometry} material={materials['MilkMaterial.003']} morphTargetDictionary={nodes.AlcalineCilinder.morphTargetDictionary} morphTargetInfluences={nodes.AlcalineCilinder.morphTargetInfluences} position={[1.265, -0.001, 2.908]} scale={[0.188, 0.015, 0.188]} />
      <mesh name="AcidCilinder" geometry={nodes.AcidCilinder.geometry} material={materials['MilkMaterial.003']} morphTargetDictionary={nodes.AcidCilinder.morphTargetDictionary} morphTargetInfluences={nodes.AcidCilinder.morphTargetInfluences} position={[2.112, -0.001, 3.149]} scale={[0.188, 0.015, 0.188]} />
    </group>
  )
}

useGLTF.preload('./horizontalTankModel/2Pales/horizontalTank2Blades.glb')
