/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\horizontalTankModel\2Pales\HorizontalTankModel2Pales.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function HorizontalTankModel2Pales(props) {
  const { nodes, materials } = useGLTF('/horizontalTankModel/2Pales/HorizontalTankModel2Pales.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.TankCilinder.geometry} material={materials.TankMaterial} position={[0.002, 2.043, 0.008]} scale={1.113} />
      <mesh geometry={nodes.Plano.geometry} material={nodes.Plano.material} position={[1.7, 2.5, -0.014]} scale={5.276} />
      <mesh geometry={nodes.MilkCilinder100.geometry} material={nodes.MilkCilinder100.material} position={[-0.026, 2.389, -0.096]} scale={[2.531, 2.531, 2.615]} />
      <mesh geometry={nodes.MilkCilinder50.geometry} material={nodes.MilkCilinder50.material} position={[-0.026, 2.389, -0.106]} scale={[2.531, 2.531, 2.615]} />
      <mesh geometry={nodes.MilkCilinder25.geometry} material={nodes.MilkCilinder25.material} position={[-0.026, 2.389, -0.096]} scale={[2.531, 2.531, 2.615]} />
      <mesh geometry={nodes.MilkCilinder75.geometry} material={nodes.MilkCilinder75.material} position={[-0.026, 2.389, -0.096]} scale={[2.531, 2.531, 2.615]} />
    </group>
  )
}

useGLTF.preload('/horizontalTankModel/2Pales/HorizontalTankModel2Pales.glb')
