/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\frontend\public\horizontalTankModel\horizontalTank1Blade.glb -o HorizontalTank1Blade.jsx 
*/

import { useGLTF } from '@react-three/drei'

export function HorizontalTank1Blade(props) {
  const { nodes, materials } = useGLTF('./horizontalTankModel/horizontalTank1Blade.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.MilkCilinder25.geometry} material={materials.MilkMaterial} position={[-0.026, 1.597, -0.122]} scale={[2.531, 2.531, 1.974]} />
      <mesh geometry={nodes.MilkCilinder50.geometry} material={materials.MilkMaterial} position={[-0.026, 1.597, -0.122]} scale={[2.531, 2.531, 1.974]} />
      <mesh geometry={nodes.MilkCilinder75.geometry} material={materials.MilkMaterial} position={[-0.026, 1.597, -0.122]} scale={[2.531, 2.531, 1.974]} />
      <mesh geometry={nodes.MilkCilinder100.geometry} material={materials.MilkMaterial} position={[-0.026, 1.597, -0.122]} scale={[2.531, 2.531, 1.974]} />
      <mesh geometry={nodes.Blade.geometry} material={materials.BladeMaterial} position={[0, 0.737, -0.077]} scale={-0.148} />
      <mesh geometry={nodes.Hatch.geometry} material={materials.HatchMaterial} position={[0, 2.377, 0.916]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.TankCilinder.geometry} material={materials.TankMaterial} position={[0.548, 0.399, -1.164]} scale={[1, 1, 0.755]} />
      <mesh geometry={nodes.BladeHat.geometry} material={materials.BladeMaterial} position={[0, 2.451, -0.081]} scale={[0.104, 0.082, 0.104]} />
      <mesh geometry={nodes.MilkCilinder10.geometry} material={materials.MilkMaterial} position={[-0.026, 1.597, -0.122]} scale={[2.531, 2.531, 1.974]} />
      <mesh geometry={nodes.MilkCilinder20.geometry} material={materials.MilkMaterial} position={[-0.026, 1.597, -0.122]} scale={[2.531, 2.531, 1.974]} />
      <mesh geometry={nodes.MilkCilinder30.geometry} material={materials.MilkMaterial} position={[-0.026, 1.597, -0.122]} scale={[2.531, 2.531, 1.974]} />
      <mesh geometry={nodes.MilkCilinder40.geometry} material={materials.MilkMaterial} position={[-0.026, 1.597, -0.122]} scale={[2.531, 2.531, 1.974]} />
      <mesh geometry={nodes.MilkCilinder60.geometry} material={materials.MilkMaterial} position={[-0.026, 1.597, -0.122]} scale={[2.531, 2.531, 1.974]} />
      <mesh geometry={nodes.MilkCilinder70.geometry} material={materials.MilkMaterial} position={[-0.026, 1.597, -0.122]} scale={[2.531, 2.531, 1.974]} />
      <mesh geometry={nodes.MilkCilinder80.geometry} material={materials.MilkMaterial} position={[-0.026, 1.597, -0.122]} scale={[2.531, 2.531, 1.974]} />
      <mesh geometry={nodes.MilkCilinder90.geometry} material={materials.MilkMaterial} position={[-0.026, 1.597, -0.122]} scale={[2.531, 2.531, 1.974]} />
      <mesh geometry={nodes.BarrelAlcaline.geometry} material={materials.BarrelMaterial} position={[0.835, 0.27, 2.695]} />
      <mesh geometry={nodes.BarrelAcid.geometry} material={materials.BarrelMaterial} position={[1.683, 0.27, 2.937]} />
      <mesh name="AlcalineCilinder" geometry={nodes.AlcalineCilinder.geometry} material={materials.AlcalineMaterial} morphTargetDictionary={nodes.AlcalineCilinder.morphTargetDictionary} morphTargetInfluences={nodes.AlcalineCilinder.morphTargetInfluences} position={[0.744, -0.001, 2.754]} scale={[0.188, 0.015, 0.188]} />
      <mesh name="AcidCilinder" geometry={nodes.AcidCilinder.geometry} material={materials.AcidMaterial} morphTargetDictionary={nodes.AcidCilinder.morphTargetDictionary} morphTargetInfluences={nodes.AcidCilinder.morphTargetInfluences} position={[1.591, -0.001, 2.996]} scale={[0.188, 0.015, 0.188]} />
    </group>
  )
}

useGLTF.preload('./horizontalTankModel/horizontalTank1Blade.glb')
