/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\frontend\public\verticalTankModel\verticalTank1Blade.glb -o VerticalTank1Blade.jsx 
*/

import { useGLTF } from '@react-three/drei'

export function VerticalTank1Blade(props) {
  const { nodes, materials } = useGLTF('./verticalTankModel/verticalTank1Blade.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Blade.geometry} material={materials.BladeMaterial} position={[-0.006, 0.495, 0.022]} scale={[-0.148, -0.188, -0.148]} />
      <mesh geometry={nodes.Hatch.geometry} material={materials.HatchMaterial} position={[0, 2.79, -0.606]} />
      <mesh geometry={nodes.BladeHat.geometry} material={materials.BladeMaterial} position={[-0.006, 2.811, 0.019]} scale={[0.061, 0.045, 0.061]} />
      <mesh geometry={nodes.BarrelAlcaline.geometry} material={materials.BarrelMaterial} position={[0.915, 0.27, 1.575]} />
      <mesh geometry={nodes.BarrelAcid.geometry} material={materials.BarrelMaterial} position={[1.763, 0.27, 1.817]} />
      <mesh geometry={nodes.TankCilinder.geometry} material={materials.TankMaterial} position={[0.391, -0.004, -0.541]} scale={[0.31, 0.169, 0.31]} />
      <mesh name="AlcalineCilinder" geometry={nodes.AlcalineCilinder.geometry} material={materials.AlcalineMaterial} morphTargetDictionary={nodes.AlcalineCilinder.morphTargetDictionary} morphTargetInfluences={nodes.AlcalineCilinder.morphTargetInfluences} position={[0.824, -0.001, 1.634]} scale={[0.188, 0.015, 0.188]} />
      <mesh name="AcidCilinder" geometry={nodes.AcidCilinder.geometry} material={materials.AcidMaterial} morphTargetDictionary={nodes.AcidCilinder.morphTargetDictionary} morphTargetInfluences={nodes.AcidCilinder.morphTargetInfluences} position={[1.671, -0.001, 1.876]} scale={[0.188, 0.015, 0.188]} />
      <mesh name="MilkCilinder" geometry={nodes.MilkCilinder.geometry} material={materials.MilkMaterial} morphTargetDictionary={nodes.MilkCilinder.morphTargetDictionary} morphTargetInfluences={nodes.MilkCilinder.morphTargetInfluences} position={[-0.002, 1.398, 0.012]} scale={[0.782, 1.311, 0.782]} />
    </group>
  )
}

useGLTF.preload('./verticalTankModel/verticalTank1Blade.glb')
